### ISSUE TITLE
Inspec Profile verifying Security Groups have FTP disabled

### ISSUE THREAD

**Issue by rbizzell40** [inspec/inspec-aws#149]
I am executing this code against aws and I am seeing an error that states 

"undefined local variable or method `aws_region' for <Class:0x00007fb44af99060>:0x00007fb44afa3178>"
The code is suppose to go through all the regions correct or do I have to define a specific region.
title 'Test AWS Security Groups Across All Regions For an Account Disallow FTP'

control 'aws-multi-region-security-group-ftp-1.0' do

  impact 1.0
  title 'Ensure AWS Security Groups disallow FTP ingress from 0.0.0.0/0.'

  aws_regions.region_names.each do |region|
    aws_security_groups(aws_region: region).group_ids.each do |security_group_id|
      describe aws_security_group(aws_region: region, group_id: security_group_id) do
        it { should exist }
        it { should_not allow_in(ipv4_range: '0.0.0.0/0', port: 21) }
      end
    end
  end
end

**Comment by omer-chefio** [comment]
Hi @rbizzell40, thanks for submitting an issue.
I tested your control and it works fine on my setup.
In order to help further on this issue, would you be able to provide a bit more information on your setup:
* What version of InSepc is being used?
* What version of the resource pack is being used?
* What command is being used to run the control?
* Which resource is missing the `aws_region` method? (Run each resource separately to identify that)
* Could you also provide a sample of your inspec.yml?

You can also check this sample [inspec.yml](https://github.com/inspec/inspec-aws/blob/master/sample_profile/inspec.yml).

**Comment by omerdemirok** [comment]
@rbizzell40, please feel free to reopen if this is still a problem.
