### ISSUE TITLE
Update docs on the proper method for creating custom local resource based on the resource pack.

### ISSUE THREAD

**Issue by aaronlippold** [inspec/inspec-aws#235]
Guidance on the correct way to create and load the libraries from the resource pack in local custom profile resources. Currently users are having issues creating custom resources based on the the backend of the resource pack.

**Comment by skpaterson** [comment]
Hi @aaronlippold, looks like there are two separate issues here.  The first is how to use profile inheritance and create custom resources.  I think this is mostly covered by the InSpec profile documentation (https://www.inspec.io/docs/reference/profiles/) but feel free to create an issue in InSpec if you feel something is missing.  

The second issue is a feature request to extend the current profile inheritance model to allow direct ruby inheritance of classes within upstream InSpec profiles.  To track that request, I created this:
https://github.com/inspec/inspec/issues/5147
Since that change would apply to all resource packs, not only inspec-aws, I will close this out for now.
