### ISSUE TITLE
describe aws_s3_bucket region should be us-east-1

### ISSUE THREAD

**Issue by jseiser** [inspec/inspec-aws#30]
### 🎛 Description

**Choose one:** 🐛 bug report

  S3 Bucket s3-my-bucket-dev
     ✔  should exist
     ✔  should not be public
     ×  region should eq "us-east-1"
     
     expected: "us-east-1"
          got: ""
     
     (compared using ==)

I know most AWS s3 bucket calls, return "" if the region is us-east-1.  I am wondering if this is the case for inspec region should eq calls as well.

### 🌍 InSpec and Platform Version

inspec version 2.2.35
OS Arch Linux

### 🤔 Replication Case

describe aws_s3_bucket('test_bucket') do
  # Check if the correct region is set
  its('region') { should eq 'us-east-1' }
end

**Comment by skpaterson** [comment]
The implementation on the bucket resource has changed, whenever picking this up please try to reproduce the above.

**Comment by skpaterson** [comment]
Thanks for opening this issue with us. Unfortunately, while I agree this can be misleading for the consumers of InSpec and the authors of controls, we do also wish to respect the underlying AWS SDK's functionality.  The AWS S3 documentation states  that if the requested Bucket's location is `us-east-1` the location string returned will be empty (https://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketGETlocation.html).   

In this instance I would recommend handling and documenting the expected behaviour in your control. Additionally you may wish to make a feature request to change this functionality with the AWS SDK team, which can be done here https://github.com/aws/aws-sdk-ruby/blob/master/FEATURE_REQUESTS.md. Thanks again, we look forward to working more with you in the future!
