### ISSUE TITLE
Exception Handling Not Working As Expected For Singular Resources

### ISSUE THREAD

**Issue by jnikles1** [inspec/inspec-aws#518]
# Describe the problem
When calling a singular resource in the aws resource pack, if an invalid name is provided, the resource doesn't appear as failed, and there is no exception message. See below for two example resources:
![image](https://user-images.githubusercontent.com/61483166/129891192-4770bfcc-6659-4816-b0d3-3cd9c4a410cb.png)

![image](https://user-images.githubusercontent.com/61483166/129891203-42979dbd-0ff7-4761-a0b9-704c02e48f96.png)

In the first example, there is not warning, and the resource doesn't appear to fail based on the resource_failed? method. In the second example, a warning is issued, but the resource still doesn't appear to fail.

## Possible Solution
in the catch_aws_errors block for the individual resources, it might make sense to add a rescue block for catching invalid resource - though this would be different for all resources. Something like this:

![image](https://user-images.githubusercontent.com/61483166/129893305-948e19da-27e1-4096-8da0-aad4dcdacf4c.png)

and you can see that it catches the error and fails the resource:
![image](https://user-images.githubusercontent.com/61483166/129893182-154b564d-ce73-4cae-a022-b0ba59e5eb9e.png)

**Comment by sathish-progress** [comment]
@jnikles1 This is an expected behaviour. Explanation follows, 

First Example: 
`aws_rds_instance` resource follows the [naming constraints defined by AWS](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_Limits.html#RDS_Limits.Constraints#:~:text=DB%20instance%20identifier) which makes your input `randomname` a valid input. Hence Even the underlying AWS APIs do not raise an error. 

Second Example: 
the error message is from AWS APIs explaining that such a region does not exist. 

So the best way to handle what you want to do is using inspec `exists?` command, to give you a quick example

```ruby
> aws_region('randomregion').exists?
[2021-09-01T22:21:54+05:30] WARN: AWS Service Error encountered running a control with Resource aws_region. Error message: Invalid region: [random]. You should address this error to ensure your controls are behaving as expected.
=> false
> aws_rds_instance('randomname').exists?
=> false
```

also if you want to use test syntax for your control profile,

```ruby
describe aws_region('randomregion') do
    it { should exist }
 end
```

also please refer here for more of [Inspec DSL](https://docs.chef.io/inspec/dsl_inspec/)
